Traceback (most recent call last):
  File "/Users/igorkapitanov/./streams_ERR.PY", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
